### ISSUE TITLE
Can't upload through source on Firefox Developer Hub

### ISSUE THREAD

**Issue by Neutrino-Tech** [tomer8007/whatsapp-web-incognito#103]
![Screenshot_20221025_153436](https://user-images.githubusercontent.com/65021172/197745446-c8785d32-d1df-4737-a32f-ece1284b0f12.png)

**Comment by tomer8007** [comment]
This is just weird, maybe try to delete the `'use strict'` in the beginning of `WhisperTextProtocol.js`

**Comment by Neutrino-Tech** [comment]
> This is just weird, maybe try to delete the `'use strict'` in the beginning of `WhisperTextProtocol.js`

Still the issue persist. 
![Screenshot_20221025_223735](https://user-images.githubusercontent.com/65021172/197843112-d64062d8-a707-42b0-bd1f-689539cec170.png)

**Comment by 9Gabr** [comment]
With the Firefox 109, I think the extension will now works, the browser now accepts the same API Extension of Chromium (Manifest v3).

**Comment by 9Gabr** [comment]
This error is happening because the file is encoded in UTF-16 which is not supported by the Firefox lint. After converting I was able to submit my port.

[WhisperTextProtocol.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10660384/WhisperTextProtocol.zip)

And here is the final version of my port, it is still being analyzed by Mozilla, but it can be used in debug mode (`about:debugging`)

[whatsapp-web-incognito-master.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10660423/whatsapp-web-incognito-master.zip)

**Comment by Neutrino-Tech** [comment]
Yes converting the file WhisperTextProtocol.js to UTF-8 does the job
