### ISSUE TITLE
Recover "Delete for me" messages

### ISSUE THREAD

**Issue by Rathod185** [tomer8007/whatsapp-web-incognito#111]
Request for the feature just like how deleted msg from sender side are not getting deleted just like make a feature that also doesn't delete the message which viewer has deleted from the phone. 

In simple word add feature that recovers both the side message (sender & receiver)  even they delete the messages. 

For eg:- If i am a receiver and i have deleted a message from phone but in doesn't get deleted from WhatsApp web just like the sender message doesn't get deleted.

**Comment by tomer8007** [comment]
Do you mean you just want the ability to restore messages you deleted for yourself?

**Comment by Rathod185** [comment]
Yes

**Comment by Rathod185** [comment]
No there is no bug at all. I request for a feature that if i delete msg from phone but it doesn't get deleted from web (reciever side) message

**Comment by Rathod185** [comment]
For eg:- if A is sender & B is reciever. Then if A delete the msg after send it doesn't get deleted in web (already having this feature) but when B delete msg from the phone which he has send to A doesn't get restore just like in case of A. 

So i request for the feature that restores the msg deleted from the B(reciever) side

**Comment by tomer8007** [comment]
OK, I understand. That's easy to implement. But why would you want such a thing? If you deleted your messages then you probably don't want to see it.

**Comment by Rathod185** [comment]
For me it's very useful bcz as a owner i have manager under me who handles my deals with the client and if he deals outside of the business i can come to know. Recently i have fired my old manager bcz i got to know he was taking commission from the clients for deal. So if you implement this feature then it will be a win win situation for me.

**Comment by tomer8007** [comment]
I'm not sure it's something everybody would want, but you can do this easily for yourself by going to this code:
https://github.com/tomer8007/whatsapp-web-incognito/blob/bc6c28492400684435a54a23b33b738b8eb3ded8/core/interception.js#L421
And add this line to the condition:
```js
||  (message.deviceSentMessage && NodeHandler.checkForMessageDeletionNode(message.deviceSentMessage.message, messageId, remoteJid));
```

**Comment by Rathod185** [comment]
Thank you sir,

But i am not a coder it will be hard for me to do something like this it will be great if you can help me in this.

**Comment by tomer8007** [comment]
Search for a file called `interception.js` on your computer. It should be under ```C:\Users\<USERNAME>\AppData\Local\Google\Chrome\User Data\Default\Extensions\badcnlhjepdmbolnedgkdpajggjogcnl``` or something similar.

**Comment by Rathod185** [comment]
Thank you bro for the help but i am also using this extension on my android phone via KIWI Browser as chrome extension are supported in it. Bcz i can't access pc everytime. So it would be great if you add this feature in extension itself and on the otherside you are saying it may be not useful to everyone you are right in this case but just adding this feature to extention will do nothing to it and as if anyone doesn't require this feature will not turn it on & if required then they will have the option for same. 

I hope you can understand me. 

Thank you for the earlier help.

**Comment by tomer8007** [comment]
I don't want to add this to the extension even as an opt-in feature because there is not enough GUI for it. What I can do is to insert this but have a javascript variable that controls it. Then you could manually turn the variable on.

**Comment by Rathod185** [comment]
bro can do one thing if you dont want to make this public can you send me
the direct .crx file with above feature  so install in my pc & phone.

bro i am not a coder even you add variable i dont know what to do with it

**Comment by tomer8007** [comment]
[WAIncognito_with_self_delete.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10527152/WAIncognito_with_self_delete.zip)

OK, yeah, here it is. Just extract and load it as unpacked extension in Developer mode.

**Comment by Rathod185** [comment]
Tried the above zip file but it doesn't work it gave bunch of errors. 
SS attached.

[Screenshots.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10528863/Screenshots.zip)

**Comment by Rathod185** [comment]
Tried this zip but this also gave errors but compared to last time less
errors.

**Comment by tomer8007** [comment]
@Rathod185 You should be able to load the last zip with the extension working at least.

**Comment by Rathod185** [comment]
Yes, the the last zip you send is working fine with previous feature but
the feature of self delete message recovery is not working at all.

And most of the errors are related to *core/interception.js:621 (anonymous
function)*

**Comment by w4po** [comment]
I can confirm that it works just fine for (delete for everyone), but it doesn't work for (delete for me)

**Comment by tomer8007** [comment]
> Yes, the the last zip you send is working fine with previous feature but
the feature of self delete message recovery is not working at all.

The zip that's supposed to work with the self delete feature is [WAIncognito_with_self_delete.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10527152/WAIncognito_with_self_delete.zip). Did you try it?

**Comment by Rathod185** [comment]
Yes sir, firstly i tried that only and the errors were found in that, also
it was not working for self delete messages. I have tried both the zips.
That you have sent.

**Comment by tomer8007** [comment]
[WhatsApp Web Incognito.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10608284/WhatsApp.Web.Incognito.zip)
Please tell me if this one works for you.

**Comment by w4po** [comment]
> [WhatsApp Web Incognito.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10608284/WhatsApp.Web.Incognito.zip) Please tell me if this one works for you.

It doesn't work with me at all for both (delete for me & delete for everyone).

The [above ](https://github.com/tomer8007/whatsapp-web-incognito/issues/111#issuecomment-1399566177) solution works for only (delete for everyone).

**Comment by tomer8007** [comment]
The last zip file should just be the original extension. I want to make sure it works as intended before I upload the one with self-delete prevention.

**Comment by w4po** [comment]
> 

For me, it works just fine for everything but self-deleted messages.
BTW, those errors he mentioned do exist even with the chrome-store original version, but it doesn't affect the functionality.

**Comment by tomer8007** [comment]
[WhatsApp Web Incognito with self-delete.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10608513/WhatsApp.Web.Incognito.zip)
OK, here's one that's supposed to show self-deleted messages.

**Comment by w4po** [comment]
> [WhatsApp Web Incognito with self-delete.zip](https://github.com/tomer8007/whatsapp-web-incognito/files/10608513/WhatsApp.Web.Incognito.zip) OK, here's one that's supposed to show self-deleted messages.

Works only for (delete for everyone) but not if I choose (delete for me).

**Comment by tomer8007** [comment]
@w4po This might only show the message you deleted for yourself if you delete it from your phone.

**Comment by w4po** [comment]
> ~@w4po This might only show the message you deleted for yourself if you delete it from your phone.~ EDIT: They seem to implement it differently now. The client would "restore" the app state with patches. So it doesn't work.
> 
> Some more investigation will be needed to implement this feature.

I wish I could help.
And thank you very much for your hard work ❤️

**Comment by Rathod185** [comment]
No this one also doesn't work it doesn't restores the self deleted
messages. If any help needed please let me know i am available for testing
& sharing results.

**Comment by Rathod185** [comment]
Good Morning sir,

Are there any updates on this feature sir ?

**Comment by tomer8007** [comment]
@Rathod185 I'm not working on it now, sorry. Currently this feature only works for "Delete for everyone" but not for "Delete for me".

**Comment by w4po** [comment]
@tomer8007 Hi, I really need this feature.. can you just point me out on how to do it?
I've tried to debug it but I don't know where to start,
When I delete a message for me the following is being sent:

```
interception.js:515 [In] Received binary with tag '' (38 bytes, decrypted)): 
interception.js:524 <notification from=​"c.us" type=​"server_sync" id=​"2196905607" t=​"1681363911">​…​</notification>​<collection name=​"regular_high" version=​"16">​</collection>​</notification>​
interception.js:652 [WhatsApp][2] -- syncd: incoming sync notification for collections
regular_high v16
```
in delete for everyone it is easy because I can follow it,

but delete for me sends just a notification and I don't know how to get the deleted message Id.

Thank you very much for your awesome support <3

**Comment by tomer8007** [comment]
@w4po The key thing to figure out is how exactly to parse the binary `patches` inside the sync messages, identify the relevant `REMOVE` mutation and block it.

![image](https://user-images.githubusercontent.com/11458759/232252096-5eeda605-e5db-4567-8a59-080351bcaaec.png)
...
![image](https://user-images.githubusercontent.com/11458759/232252472-31c5e740-bd2f-4440-9fef-675bde01250e.png)

It also appears that:
1. The sync notifications could be encrypted with keys that you get earlier as a message.
2. the patches are in binary format and represent SQL-like mutations (?)
3. There are MACs and snapshot and hashes and other things that might complicate skipping patches ("Anti-Tampering").

I recommend you to:
1. Start by reading the [Whatsapp Security Whitepaper](https://scontent.ftlv5-1.fna.fbcdn.net/v/t39.8562-6/328495424_498532869106467_756303412205949548_n.pdf?_nc_cat=104&ccb=1-7&_nc_sid=ad8a9d&_nc_ohc=j4GJeJsvRcIAX9ZxsGv&_nc_ht=scontent.ftlv5-1.fna&oh=00_AfCImr7oImuPajc_mCWMrvRsmx92UF8pL-wLeG_rhOO7zg&oe=643F38BC), specifically the section "App State Syncing Security" to get a high-level idea of syncs and patches.
2. Follow the debug logs in the console, and search them in WhatsApp's javascript code (after beautify). You can also debug it. It will help to better figure out the flow.
3. Look at the recently [leaked proto files of WhatsApp](https://github.com/nlitsme/whatsapp-apk-proto) (check `e2e.proto`) to better understand the protocol.

It is possible that because of the anti-tampering the only options would be one of:
1. Hook interesting javascript functions using `moduleRaid`
2. Instead of trying to remove the mutation, save it to our `deletedMsgs` table and restore it "manually" later.

I think the second option above is the one to go. If you manage to do something, keep me updated.

**Comment by jccricket** [comment]
I'm looking at it...
I have played a bit with the debugger and start to understand the logic of interception.js
But my knowledge and understanding is limited.

In previous I can read:
2. Instead of trying to remove the mutation, save it to our deletedMsgs table and restore it "manually" later.

I then started to think about collecting both incoming and outgoing messages and save them to a DB, replicating function saveDeletedMessage.
I know this is most probably not the best, but I take it as an exercise to understand better how all this works.

For incoming messages, I have introduced a piece of code in 
NodeHandler.onMessageNodeReceived function
in order to read encNodes variable and extract deviceSentMessage.message.extendedTextMessage.text and save it to a DB or anywhere else.

For outgoing messages, I do not understand the logic of the "nodes" that do not share the same structure, and I can't find any "text" field...

Maybe the approach is stupid, but I was thinking that if I'm able to "collect" outgoing messages (starting with text only), I can store them in DB as well, and in case I use "delete for me", then the message would still be in the DB.

Is there a way to replicate NodeHandler.onMessageNodeReceived but for NodeSent !?
I assume so, but I'm a bit lost with the node, messageNode, manipulatedNode, decryptedFrame, etc.
Shall I look more at 
NodeHandler.onSentMessageNode
Or is there a better place to "collect" sent messages ?

**Comment by tomer8007** [comment]
> Is there a way to replicate NodeHandler.onMessageNodeReceived but for NodeSent !?

This is something I thought about in the past, but it'll require some hacks because unlike in the receiving flow, in the sending flow the message will be encrypted with a key that is no longer available as far as I can tell. So now you can't really collect outgoing messages until I'll implement that.

**Comment by jccricket** [comment]
Thank you for your reply.
In case a basic coder like me can help, I would be happy to investigate deeper and offer some of my time here.
