### ISSUE TITLE
[Request] Would it be possible to port the extension to Safari?

### ISSUE THREAD

**Issue by mendeel** [tomer8007/whatsapp-web-incognito#30]
Hello, guys! I love your work and the extension is amazing, it makes me able to be free to read the groups from work and not worry hahaha

As the title says, I have no idea about the current state of Safari Extensions development, APIs and stuff and, as such, I'd kindly like to ask you: do you think it would be possible to port this extension to Safari for macOS?

Thanks for your attention and have a nice week :)

**Comment by mendeel** [comment]
Just found out that latest Safari v14 supports Web Extensions and you can convert some extensions using Xcode: https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by tomer8007** [comment]
I wonder how different that would look from the original extension.

**Comment by mendeel** [comment]
I just tried following the tutorial in the link above and it actually seems to be working:
![WAIncognito Safari](https://user-images.githubusercontent.com/1301796/96034044-58c18600-0e37-11eb-9b81-a35b65c00973.png)

**Comment by thomasqueirozb** [comment]
> Hmm, I'm not sure what's missing. @thomasqueirozb Do you know Safari extensions?

I'm not a mac user but since it was mentioned that safari has Web Extension support the only thing I see that could go wrong is this

https://github.com/tomer8007/whatsapp-web-incognito/blob/1e9c17f8d0acb15ba96012d74453208ad34bd075/styles.css#L20-L24

Since the css references a `moz-extension://` url and is dependent of `-moz-appearance:none`.

This was made to work with Firefox **only** and overrides the previously defined `chrome-extension://` url
https://github.com/tomer8007/whatsapp-web-incognito/blob/1e9c17f8d0acb15ba96012d74453208ad34bd075/styles.css#L11

Other than this I'm not sure I have much to offer on this matter

**Comment by tomer8007** [comment]
This also remainds me of dark theme support...

**Comment by eduardow9** [comment]
> I just tried following the tutorial in the link above and it actually seems to be working:
> ![WAIncognito Safari](https://user-images.githubusercontent.com/1301796/96034044-58c18600-0e37-11eb-9b81-a35b65c00973.png)

Hi mendell! Could you please help me with a tutorial on how to install this extension in Safari? I'm not a programmer, but I have an average knowledge. Thank you very much if you can help me.
