### ISSUE TITLE
[Feature Request] Whatsapp desktop version implementation

### ISSUE THREAD

**Issue by MacgyverJohnson** [tomer8007/whatsapp-web-incognito#69]
HI @tomer8007 ,

Totally loved your implementation of this whatsapp web incognito....Could it be implemented with whatsapp desktop. This might be possible using the same way that @m4heshd from [whatsapp-desktop-dark](https://github.com/m4heshd/whatsapp-desktop-dark/tree/master/themes) can mod whatsapp desktop (although he just modifies css) 

Best regards.

**Comment by tomer8007** [comment]
Hi, this was previously asked in #7. Basically, I never tried, but it probably isn't hard.

**Comment by m4heshd** [comment]
> although he just modifies css

It wasn't just CSS. The theme switching button which I added in later updates were done via injecting JS. BTW, thanks for the tag because I just discovered this cool utility because of that.

> Basically, I never tried, but it probably isn't hard.

I can guarantee that it would be quite difficult. The issue is, a lot of Chrome's dev scopes aren't available for Electron which makes it difficult to pre-inject a renderer controller. Electron does have something dedicated for that called `preload` but that requires a lot of effort injecting that. The most horrifying part for me was reading through thousands of obfuscated lines of code to find a place to inject some debugger access code. Then the entry point for renderer injection. Things kinda become a breeze after that though. Also what I discovered while doing WADark was the WA web and desktop are two vastly different code bases. They do share some stuff but hardly similar. 

Conclusion here is, we can't use the same set of code on both applications and even if we managed to get it working, maintaining it would be hell. But I'm positive that it isn't impossible. Just difficult. That's just my opinion and that is mostly because I can't remember anything from the process of maintaining that project now. 😁

**Comment by MacgyverJohnson** [comment]
> Conclusion here is, we can't use the same set of code on both applications and even if we managed to get it working, maintaining it would be hell. But I'm positive that it isn't impossible. Just difficult. That's just my opinion and that is mostly because I can't remember anything from the process of maintaining that project now. 😁

Thanks for the clarification....
