### ISSUE TITLE
WhatsApp Standalone Support

### ISSUE THREAD

**Issue by timeakesmarky** [tomer8007/whatsapp-web-incognito#7]
Hello,

Thanks for this tool.
Can you support whatsapp standalone client?

Or can I unpack app.asar and inject these extension files to it? Would it work?

**Comment by tomer8007** [comment]
I never worked with the Electron framework, but looks like there are plentry of resources on the internet for trying to insert Chrome extensions into Electron apps (like [this](https://github.com/getstation/electron-chrome-extension), [this](https://stackoverflow.com/questions/53341132/how-can-i-add-a-custom-chrome-extension-to-my-electron-app) and [more](https://github.com/electron/electron/issues/1498)).

I don't know whether or not the DOM is the same in the standalone app, though. That's an important question.

I can tell you that at least if you're trying to inject these files without Chrome-specific adaptations you'd have to fiddle with `core_injection.js` and `background.js`.

`core_injection.js` is the first file that runs as a content script and injects the other scripts to the real DOM, and it's using the `chrome.extension`  API (so you'll need to change this line).

`background.js` uses Chrome APIs too to save the settings of the user persistently, so an alternative way of doing that would be needed.

Also it's important to make the overall injection so that `core_injection.js` will run **before any other WhatsApp script**, otherwise the `WebSocket `interception won't work.

**Comment by timeakesmarky** [comment]
The app.asar can be found in the nupkg.
https://web.whatsapp.com/desktop/windows/release/x64/WhatsApp-0.3.4479-full.nupkg

I opened it with winrar and extracted the app.asar with node.

What do I need to check and find out if it's the same. If it's not the same, you can close this issue. Not worth it.

**Comment by tomer8007** [comment]
I would start by running `document.getElementsByClassName("_3j8Pd")` in the javasciprt console and see if I get all the menu items at the top.

If you get them, I think it's a pretty good indication it's the same.

**Comment by timeakesmarky** [comment]
Oh, I don't know how to do that, I'm not programmatically well-versed.
